# Site
name: 'Blog de Bryan Oroxon'
description: 'En este sitio encontrarás mis intereses como Xamarin, Azure, C#, Bots y nuevas tecnologías que pueda compartir, como dijo Miguel de Icazá "Con interés cualquiera aprendé". Así que aprendamos juntos.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    bryan:
      name:           Bryan Oroxon
      site:           https://github.com/BryanOroxon
      avatar:         assets/images/img_bryan.jpg
      bio:            "Me gustan desarrollar y construir soluciones que brinden valor, algunos de mis intereses son IT Pro, Xamarin Form, Xamarin Android, Xamarin iOS, C#, Azure, Bot Framework y Cisco. Me gustan Construir con Lego."
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/BryanOroxon
      
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Bryan Oroxon
      avatar: assets/images/img_bryan.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]